name: Deploy to Vercel

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: team_XCEh8Whg7sXweoLP2nKed2iI
          VERCEL_PROJECT_ID: prj_7YkIq9QPjkpJj7LI4jb4iexA13bA
